services:
  mysql:
    image: mysql:8.4
    container_name: biblioteca-mysql

    env_file:
      - .env

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql_data:
